name: 'Snaplet import'
on:
  push:
  # schedule:
  #   - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  sync-database:
    runs-on: ubuntu-latest
    env:
      SOURCE_DATABASE_URL: ${{ secrets.SOURCE_DATABASE_URL }}
      TARGET_DATABASE_URL: ${{ secrets.DESTINATION_DATABASE_URL }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Install Snaplet CLI
        run: curl -sL https://app.snaplet.dev/get-cli/ | bash

      # Import schema from source DB to target DB using pg_dump
      - name: Import schema
        run: pg_dump $SOURCE_DATABASE_URL --schema-only | psql $TARGET_DATABASE_URL;

      # Configure Snaplet
      - name: Configure Snaplet
        run: snaplet config setup $TARGET_DATABASE_URL

      # Capture snapshot from source
      - name:
        run: SNAPLET_SOURCE_DATABASE_URL=$SOURCE_DATABASE_URL snaplet snapshot capture

      # Restore snapshot into target
      - name: Restore snapshot into target database
        run: snaplet snapshot restore -y
